version: '3.8'

services:
  ecosurprise-app:
    build: .
    container_name: ecosurprise-go
    restart: always
    environment:
      DB_HOST: ${DB_HOST:-db:3306}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-ecosurprise}
      JWT_SECRET: ${JWT_SECRET:-ecosurprise_secret_key_2024_secure_and_long_enough_for_hs512}
      PORT: ${PORT:-8080}
      ENV: ${ENV:-production}
      APP_IP: ${APP_IP:-*}
    ports:
      - "8080:8080"
    volumes:
      app_uploads:
        driver: local
